//
//  SearchCountriesProtocols.swift
//  RestContries
//
//  Created Adam on 7/17/20.
//  Copyright © 2020 TaskApp. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchCountriesWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchCountriesPresenterProtocol: class {

}

//MARK: Interactor -
protocol SearchCountriesInteractorProtocol: class {

  var presenter: SearchCountriesPresenterProtocol?  { get set }
}

//MARK: View -
protocol SearchCountriesViewProtocol: class {

  var presenter: SearchCountriesPresenterProtocol?  { get set }
}
