//
//  SearchCountriesRouter.swift
//  RestContries
//
//  Created Adam on 7/17/20.
//  Copyright © 2020 TaskApp. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCountriesRouter: SearchCountriesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SearchCountriesViewController(nibName: nil, bundle: nil)
        let interactor = SearchCountriesInteractor()
        let router = SearchCountriesRouter()
        let presenter = SearchCountriesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
