//
//  SearchCountriesPresenter.swift
//  RestContries
//
//  Created Adam on 7/17/20.
//  Copyright © 2020 TaskApp. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCountriesPresenter: SearchCountriesPresenterProtocol {

    weak private var view: SearchCountriesViewProtocol?
    var interactor: SearchCountriesInteractorProtocol?
    private let router: SearchCountriesWireframeProtocol

    init(interface: SearchCountriesViewProtocol, interactor: SearchCountriesInteractorProtocol?, router: SearchCountriesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
