//
//  SearchCountriesViewController.swift
//  RestContries
//
//  Created Adam on 7/17/20.
//  Copyright © 2020 TaskApp. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchCountriesViewController: UIViewController, SearchCountriesViewProtocol {

	var presenter: SearchCountriesPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
